### ISSUE TITLE
question description default

### ISSUE THREAD

**Issue by dvs1** [SunyataZero/well-being-diary#5]
I would make the question description that same as the question title,
unless a question description is entered.
Otherwise, if I don't enter a question description I see "long question text"
above the answer entry.

**Comment by SunyataZero** [comment]
@dvs1 Thanks for writing this issue, i will look into this. Btw if you like you can join us here if you want to discuss the future of the application: https://gitter.im/well-being-diary/Lobby

**Comment by SunyataZero** [comment]
@dvs1 I've now moved the question title to be positioned just above the edit/entry area, can you verify and if everything is okay close this issue? Thanks again for your help! Kind Regards, Tord

**Comment by dvs1** [comment]
I see the question now, but also "long question text".

I would set the default to be blank.

**Comment by SunyataZero** [comment]
@dvs1 Okay, i don't know why but i missed this before, it should be fixed now!

**Comment by dvs1** [comment]
:+1:
