### ISSUE TITLE
"add and next" button

### ISSUE THREAD

**Issue by dvs1** [SunyataZero/well-being-diary#6]
The "add and next" button doesn't seem to do anything.

**Comment by SunyataZero** [comment]
Good find! Thank you

**Comment by SunyataZero** [comment]
@dvs1 I've been thinking about this, is this something that you would find important or not so useful? I'm considering if we want to keep this or not, what are your thoughts about this?

**Comment by SunyataZero** [comment]
I've removed this button for now, (maybe it will be added again later)
